spring:
  profiles: #配置本机配置中心
    active: native
  application:
    name: oom-core-config
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native: #配置本机配置中心 下面是路径
          searchLocations: /Users/dengtaiyang/workSpace/oom/oom-core/oom-core-config/src/main/resources/dty/
#        git:  配置GIT远程厂库
#          uri: https://github.com/dj714330240/oom # 远程git仓库的地址
#          username:
#          password:
#          basedir: E:\Java_IDEA\config\basedir  # 可以使用这个配置项来指定本地git仓库的路径
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8974